import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Footer } from '@/components/Footer/Footer';
import { Header } from '@/components/Header/Header';
import { ReduxProvider } from '@/redux/ReduxProvider';

import styles from './global.module.scss';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'next learning',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<ReduxProvider>
			<html lang='en'>
				<body className={`${montserrat.className} ${styles.reset}`}>
					<Header />
					<main className={styles.container}>{children}</main>
					<Footer />
				</body>
			</html>
		</ReduxProvider>
	);
}
